apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-app
  labels:
    app: to-do-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
        - name: application
          image: docker.io/samiraafrin/to-do-app-web
          imagePullPolicy: Always
          ports:
            - containerPort: 8000