version: "3.7"
services:
  web:
    build:
      context: .
    #container_name: todo_api
    ports:
      - 8000:8000
    depends_on:
      - mysql # 1 part
    volumes:
    - ./config.json:/config.json

  mysql:   # 2 part
    image: mysql # this name has to be the image name in the docker hub
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"  # 3307:3306
    environment:
      - MYSQL_DATABASE=recordings
      - MYSQL_ROOT_PASSWORD=123

  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - mysql  # 3 part

  # all the part (1,2,3) has to be same and the host name in the config.json files